### ISSUE TITLE
Urgent! How did u generate submission package for coursera upload??

### ISSUE THREAD

**Issue by UtkarshK10** [niravjdn/Coursera---Building-Cloud-Services-with-the-Java-Spring-Framework#1]
i tried following the documentation, was not able to follow

**Comment by niravjdn** [comment]
what is the error you got? I have compiled this project using eclipse.

**Comment by UtkarshK10** [comment]
Can u explain step by step how to compile the project using eclipse and generate the submission package?

**Comment by niravjdn** [comment]
You will have to import the project as a grade then follow this instructions.

To get an estimated score for your solution, right-click on AutoGrading (not AutoGradingTest) and Run As->Java Application. The AutoGrading application will run AutoGradingTest and then print a summary of the test results and your score to the Eclipse Console (Window->Show View->Console). The AutoGrading application will also create a submission package that you will submit as the solution to the assignment in Coursera.

**Comment by niravjdn** [comment]
Once you are able to import as a Gradle project, download all Gradle dependencies. Eclipse is bad in managing Gradle dependencies, you can use intelliJ.

**Comment by UtkarshK10** [comment]
Yes it worked now. Thanks a lot for your help! :)
